package com.example.sunandmoon.util

import com.example.sunandmoon.R

val weatherIcons : Map<String,List<Int>> = mapOf(
    "clearsky" to listOf(R.drawable.clearsun, R.drawable.clearnight),
    "cloudy" to listOf(R.drawable.cloudy, R.drawable.cloudy),
    "fair" to listOf(R.drawable.fairsun, R.drawable.fairnight),
    "fog" to listOf(R.drawable.fog, R.drawable.fog),
    "heavyrain" to listOf(R.drawable.heavyrain, R.drawable.heavyrain),
    "heavyrainandthunder" to listOf(R.drawable.heavyrainthunder, R.drawable.heavyrainthunder),
    "heavyrainshowers" to listOf(R.drawable.heavyrain, R.drawable.heavyrain),
    "heavyrainshowersandthunder" to listOf(R.drawable.heavyrainthunder, R.drawable.heavyrainthunder),
    "heavysleet" to listOf(R.drawable.heavysleet, R.drawable.heavysleet),
    "heavysleetandthunder" to listOf(R.drawable.heavyrainthunder, R.drawable.heavyrainthunder),
    "heavysleetshowers" to listOf(R.drawable.heavysleet, R.drawable.heavysleet),
    "heavysleetshowersandthunder" to listOf(R.drawable.heavyrainthunder, R.drawable.heavyrainthunder),
    "heavysnow" to listOf(R.drawable.snow, R.drawable.snow),
    "heavysnowandthunder" to listOf(R.drawable.heavyrainthunder, R.drawable.heavyrainthunder),
    "heavysnowshowers" to listOf(R.drawable.snow, R.drawable.snow),
    "heavysnowshowersandthunder" to listOf(R.drawable.heavyrainthunder, R.drawable.heavyrainthunder),
    "lightrain" to listOf(R.drawable.rain, R.drawable.rain),
    "lightrainandthunder" to listOf(R.drawable.rainthunder, R.drawable.rainthunder),
    "lightrainshowers" to listOf(R.drawable.rain, R.drawable.rain),
    "lightrainshowersandthunder" to listOf(R.drawable.rainthunder, R.drawable.rainthunder),
    "lightsleet" to listOf(R.drawable.lightsleet, R.drawable.lightsleet),
    "lightsleetandthunder" to listOf(R.drawable.rainthunder, R.drawable.rainthunder),
    "lightsleetshowers" to listOf(R.drawable.lightsleet, R.drawable.lightsleet),
    "lightsnow" to listOf(R.drawable.snow, R.drawable.snow),
    "lightsnowandthunder" to listOf(R.drawable.rainthunder, R.drawable.rainthunder),
    "lightsnowshowers" to listOf(R.drawable.snow, R.drawable.snow),
    "lightssleetshowersandthunder" to listOf(R.drawable.rainthunder, R.drawable.rainthunder),
    "lightssnowshowersandthunder" to listOf(R.drawable.rainthunder, R.drawable.rainthunder),
    "partlycloudy" to listOf(R.drawable.partlycloudly, R.drawable.partlycloudly),
    "rain" to listOf(R.drawable.rain, R.drawable.rain),
    "rainandthunder" to listOf(R.drawable.rainthunder, R.drawable.rainthunder),
    "rainshowers" to listOf(R.drawable.rain, R.drawable.rain),
    "rainshowersandthunder" to listOf(R.drawable.rainthunder, R.drawable.rainthunder),
    "sleet" to listOf(R.drawable.lightsleet, R.drawable.lightsleet),
    "sleetandthunder" to listOf(R.drawable.rainthunder, R.drawable.rainthunder),
    "sleetshowers" to listOf(R.drawable.lightsleet, R.drawable.lightsleet),
    "sleetshowersandthunder" to listOf(R.drawable.rainthunder, R.drawable.rainthunder),
    "snow" to listOf(R.drawable.snow, R.drawable.snow),
    "snowandthunder" to listOf(R.drawable.rainthunder, R.drawable.rainthunder),
    "snowshowers" to listOf(R.drawable.snow, R.drawable.snow),
    "snowshowersandthunder" to listOf(R.drawable.rainthunder, R.drawable.rainthunder)
)